### ISSUE TITLE
Project should be "archived" on Github

### ISSUE THREAD

**Issue by holmboe** [SELinuxProject/cil#10]
According to the README this Github repo is not used anymore, and thus should be archived.

`NOTE: CIL has been merged into the SELinux Userspace repository. All future changes will be made there.`

See https://github.com/SELinuxProject/cil/settings

**Comment by maage** [comment]
C-code is in
https://github.com/SELinuxProject/selinux/tree/master/libsepol/cil/src
but documentation / wiki is not merged/migrated yet

**Comment by pcmoore** [comment]
I'm archiving this repository as I type this ...
