### ISSUE TITLE
Document all implemented token types

### ISSUE THREAD

**Issue by maage** [SELinuxProject/cil#11]
At: https://github.com/SELinuxProject/cil/wiki#basic-token-types
there is missing token types that are currently used
- path, see genfscon in base module
  I wonder why it is not quoted string like in filecon
- hex number, used in allowx even when source uses decimal numbers
  you need to create your own module to see this

**Comment by pcmoore** [comment]
The SELinux CIL toolchain has been merged into the main SELinux userspace repository, please follow up there as this repository is being archived.

* https://github.com/SELinuxProject/selinux
