### ISSUE TITLE
How can I handle an error on installing SELinux policy

### ISSUE THREAD

**Issue by JayJay-K** [SELinuxProject/cil#12]
I'm afraid I don't know whether this 'issue' board is proper to discuss or not.
If it's not proper, please let me know, I'm going to delete it immediately.

Now I'm trying to install the SELinux policy that I made. But I met error like following:

Failed to resolve filecon statement at /var/lib/selinux/targeted/tmp/modules/400/mypolicy/cil:303 
semodule: Failed! 
install failed :

I hope to know how can I handle this error. How can I find the error point in the .te or .fc file? 
What does the number '303' mean? Is it a line number? But a cil file is binary. 
Could you please let me know a way to handle this error?

**Comment by fishilico** [comment]
Hello,

> What does the number '303' mean? Is it a line number? But a cil file is binary.

303 is a line number, as a CIL file is a text file. Sometimes it can be compressed with bzip2 and using `bzcat` is possible, to decompress it. If the input file was a compiled (binary) `.pp` file, you can use `/usr/libexec/selinux/hll/pp < mypolicy.pp` to display the CIL policy which is used by `semodule`.

**Comment by JayJay-K** [comment]
Thank you. It's helpful to me.
