### ISSUE TITLE
"make unit" fails

### ISSUE THREAD

**Issue by fishilico** [SELinuxProject/cil#5]
Hi,
I am trying to build the unit tests using `make unit` (following README instructions) and this currently fails:

```
test/unit/CilTest.c: In function 'gen_test_tree':
test/unit/CilTest.c:101:25: error: 'CIL_PARSE_NODE' undeclared (first use in this function)
          node->flavor = CIL_PARSE_NODE;
```

Replacing `CIL_PARSE_NODE` with `CIL_NODE` fixes this issue, but then the build fails in an other file (for example because `cil_copy_conditional` does not exist).

In short, `make unit` looks like being currently completely broken.

**Comment by pcmoore** [comment]
Following a discussion with the SELinux maintainers, this repository is being archived so I'm closing this issue.
