### ISSUE TITLE
Cil not building

### ISSUE THREAD

**Issue by EliasCaplan** [SELinuxProject/cil#8]
I cloned the repository and then switched into the "cil" directory and when I run the first "make" command I get this error:

"cc -Wall -Wshadow -Wextra -Wundef -Wmissing-format-attribute -Wcast-align -Wstrict-prototypes -Wpointer-arith -Wunused -O2 -I./include -I/usr/include -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -c -o secilc.o secilc.c
secilc.c:30:20: fatal error: stdlib.h: No such file or directory
compilation terminated.
Makefile:60: recipe for target 'secilc.o' failed
make: **\* [secilc.o] Error 1
"

Not sure on how to fix it.

**Comment by stevedlawrence** [comment]
The CIL repo has been merged into libsepol and secilc in the SELinux userspace repo (http://github.com/SELinuxProject/selinux). So this one is no longer supported. It is here purely for historical purposes. Please checkout the selinux userspace repo and try building that. The README file has instructions on building, including necessary dependencies. If you need further help building, please email the selinux mailing list at selinux@tycho.nsa.gov (subscribe via email to selinux-join@tycho.nsa.gov).

**Comment by EliasCaplan** [comment]
Thanks Steve for the information and I just sent my question to the selinux mailing list because I am still not getting it to build.
